baseURL: https://antenna-three.github.io/
title: antenna-three.github.io
theme: PaperMod
defaultcontentlanguage: ja

paginate: 5
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  title: antenna-three.github.io
  description: antenna-three's blog and portfolio
  author: antenna-three
  keywords: [blog, portfolio]

  profileMode:
    enabled: true
    title: antenna-three
    subtitle: IT engineer
    imageUrl: images/profile.jpg
    imageWidth: 120
    imageHeight: 120

  socialIcons:
    - name: github
      url: https://github.com/antenna-three
    - name: twitter
      url: https://twitter.com/antenna_three

menu:
  main:
    - identifer: blog
      name: blog
      url: /blog
      weight: 10
    - identifer: about
      name: about
      url: /about
      weight: 10
    - identifer: works
      name: works
      url: /works
      weight: 10
