baseURL: https://antenna-three.github.io/
title: antenna-three.github.io
theme: hugo-coder
defaultcontentlanguage: ja

paginate: 20

pygmentsstyle: bw
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

disqusShortname: antenna-three

params:
  author: antenna-three
  info: IT Engineer at pluszero
  description: antenna-three's blog and portfolio
  keywords: blog,developer,personal
  katex: true

  social:
    - name: GitHub
      icon: fa fa-github fa-2x
      weight: 1
      url: https://github.com/antenna-three
    - name: Twitter
      icon: fa fa-twitter fa-2x
      weight: 2
      url: https://twitter.com/antenna_three

menu:
  main:
    - name: Blog
      weight: 1
      url: posts/
    - name: About
      weight: 1
      url: about/
